export const PrefsFields = {
    HISTORY_SIZE                    : 'history-size',
    CACHE_FILE_SIZE                 : 'cache-size',
    CACHE_ONLY_FAVORITE             : 'cache-only-favorites',
    CONFIRM_ON_CLEAR                : 'confirm-clear',
    MOVE_ITEM_FIRST                 : 'move-item-first',
    ENABLE_KEYBINDING               : 'enable-keybindings',
    KEEP_SELECTED_ON_CLEAR          : 'keep-selected-on-clear',
    BINDING_TOGGLE_POPUP            : 'toggle-popup',
    BINDING_CLEAR_HISTORY           : 'clear-history',
    BINDING_PRIVATE_MODE            : 'private-mode-binding',
    CLEAR_ON_BOOT                   : 'clear-on-boot',
    AUTO_PASTE                      : 'auto-paste',
    POPUP_POSITION_MODE             : 'popup-position-mode',
    MAX_POPUP_PAGES                 : 'popup-pages',
    CACHE_IMAGES                    : 'cache-images',
    EXCLUDED_APPS                   : 'excluded-apps',
    CLEAR_HISTORY_ON_INTERVAL       : 'clear-history-on-interval',
    CLEAR_HISTORY_INTERVAL          : 'clear-history-interval',
    NEXT_HISTORY_CLEAR              : 'next-history-clear',
    CASE_SENSITIVE_SEARCH           : 'case-sensitive-search',
    REGEX_SEARCH                    : 'regex-search',
};
