#!/usr/bin/env python3
"""Build src/translations.js from locale/*/LC_MESSAGES/waytoclip.po.

Generates a committed JS module exporting TRANSLATIONS = { lang: {msgid: msgstr} }.
Only non-empty, non-fuzzy, non-obsolete entries are included, so the runtime
override falls back to native gettext (system language / English) on misses.

Usage: python3 tools/build-translations.py
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCALE_DIR = ROOT / "locale"
OUT = ROOT / "src" / "translations.js"


def parse_po(path):
    """Minimal .po parser returning {msgid: msgstr} for usable entries."""
    text = path.read_text(encoding="utf-8")
    entries = {}
    # Split into blocks separated by blank lines.
    blocks = re.split(r"\n\s*\n", text)
    for block in blocks:
        lines = block.strip().splitlines()
        if not lines:
            continue
        # Skip obsolete (#~) blocks and headers (empty msgid).
        if any(l.lstrip().startswith("#~") for l in lines):
            continue
        is_fuzzy = any(l.strip() == "#, fuzzy" or l.startswith("#,") and "fuzzy" in l for l in lines)
        msgid_parts = []
        msgstr_parts = []
        section = None
        for line in lines:
            s = line.strip()
            if s.startswith("#"):
                continue
            m = re.match(r'^(msgid|msgstr)\s+"(.*)"$', s)
            if m:
                section = m.group(1)
                val = m.group(2)
                if section == "msgid":
                    msgid_parts.append(val)
                else:
                    msgstr_parts.append(val)
                continue
            m2 = re.match(r'^"(.*)"$', s)
            if m2 and section:
                if section == "msgid":
                    msgid_parts.append(m2.group(1))
                else:
                    msgstr_parts.append(m2.group(1))
        # Unescape standard PO escapes.
        def unescape(s):
            return (
                s.replace(r"\"", '"')
                .replace(r"\n", "\n")
                .replace(r"\t", "\t")
                .replace(r"\\", "\\")
            )

        msgid = unescape("".join(msgid_parts))
        msgstr = unescape("".join(msgstr_parts))
        if not msgid:
            continue  # header
        if is_fuzzy:
            continue
        if not msgstr:
            continue
        # Skip plural-form entries (not used by this extension).
        if "msgid_plural" in block:
            continue
        entries[msgid] = msgstr
    return entries


def js_str(s):
    # JSON string syntax is valid JS (UTF-8 kept readable).
    return json.dumps(s, ensure_ascii=False)


def main():
    if not LOCALE_DIR.is_dir():
        print(f"locale dir not found: {LOCALE_DIR}", file=sys.stderr)
        return 1
    langs = sorted(p.name for p in LOCALE_DIR.iterdir() if p.is_dir())
    all_entries = {}
    for lang in langs:
        po = LOCALE_DIR / lang / "LC_MESSAGES" / "waytoclip.po"
        if not po.is_file():
            print(f"warning: missing {po}", file=sys.stderr)
            continue
        entries = parse_po(po)
        all_entries[lang] = entries
        print(f"{lang}: {len(entries)} translated strings")

    lines = [
        "/**",
        " * Runtime translation catalogs for the language override setting.",
        " *",
        " * AUTO-GENERATED by tools/build-translations.py - do not edit by hand.",
        " * Source of truth is locale/<lang>/LC_MESSAGES/waytoclip.po.",
        " * Only non-empty, non-fuzzy entries are included; misses fall back",
        " * to native gettext (system language / English).",
        " */",
        "",
        "export const TRANSLATIONS = {",
    ]
    for lang in langs:
        entries = all_entries.get(lang, {})
        lines.append(f"    {lang_to_key(lang)}: {{")
        for msgid in sorted(entries):
            msgstr = entries[msgid]
            lines.append(f"        {js_str(msgid)}: {js_str(msgstr)},")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


def lang_to_key(lang):
    # JS object keys: quote anything non-identifier-safe (pt_BR, fr_FR, zh_CN).
    if re.match(r"^[A-Za-z_$][A-Za-z0-9_$]*$", lang):
        return lang
    return f'"{lang}"'


if __name__ == "__main__":
    sys.exit(main())
