export const PrefsFields = {
    HISTORY_SIZE                    : 'history-size',
    CACHE_FILE_SIZE                 : 'cache-size',
    CACHE_ONLY_FAVORITE             : 'cache-only-favorites',
    CONFIRM_ON_CLEAR                : 'confirm-clear',
    MOVE_ITEM_FIRST                 : 'move-item-first',
    ENABLE_KEYBINDING               : 'enable-keybindings',
    KEEP_SELECTED_ON_CLEAR          : 'keep-selected-on-clear',
    BINDING_TOGGLE_POPUP            : 'toggle-popup',
    BINDING_CLEAR_HISTORY           : 'clear-history',
    BINDING_PRIVATE_MODE            : 'private-mode-binding',
    CLEAR_ON_BOOT                   : 'clear-on-boot',
    AUTO_PASTE                      : 'auto-paste',
    POPUP_POSITION_MODE             : 'popup-position-mode',
    MAX_POPUP_PAGES                 : 'popup-pages',
    LIMIT_POPUP_PAGES               : 'limit-popup-pages',
    SHOULD_CACHE_IMAGES             : 'should-cache-images',
    EXCLUDED_APPS                   : 'excluded-apps',
    TERMINAL_APPS                   : 'terminal-apps',
    CLEAR_HISTORY_ON_INTERVAL       : 'clear-history-on-interval',
    CLEAR_HISTORY_INTERVAL          : 'clear-history-interval',
    NEXT_HISTORY_CLEAR              : 'next-history-clear',
    CASE_SENSITIVE_SEARCH           : 'case-sensitive-search',
    REGEX_SEARCH                    : 'regex-search',
    IMAGE_PREVIEW_SIZE              : 'image-preview-size',
    SHOW_SHORTCUT_HINTS             : 'show-shortcut-hints',
    IGNORE_SECRET_MIMETYPES         : 'ignore-secret-mimetypes',
    LOCAL_SEARCH                    : 'local-search',
    LOCAL_DELETE_ENTRY              : 'local-delete-entry',
    LOCAL_PRIVATE_MODE              : 'local-private-mode',
    LOCAL_PAGE_NEXT                 : 'local-page-next',
    LOCAL_PAGE_PREVIOUS             : 'local-page-previous',
    LOCAL_MOVE_UP                   : 'local-move-up',
    LOCAL_MOVE_DOWN                 : 'local-move-down',
    LOCAL_CONFIRM                   : 'local-confirm',
    LOCAL_CLOSE                     : 'local-close',
    LOCAL_CASE_SENSITIVE            : 'local-case-sensitive',
    LOCAL_REGEX_SEARCH              : 'local-regex-search',
    LOCAL_TOGGLE_FAVORITE           : 'local-toggle-favorite',
    LOCAL_FAVORITES_VIEW            : 'local-favorites-view',
    LOCAL_QUICK_SELECT_1            : 'local-quick-select-1',
    LOCAL_QUICK_SELECT_2            : 'local-quick-select-2',
    LOCAL_QUICK_SELECT_3            : 'local-quick-select-3',
    LOCAL_QUICK_SELECT_4            : 'local-quick-select-4',
    LOCAL_QUICK_SELECT_5            : 'local-quick-select-5',
    LOCAL_QUICK_SELECT_6            : 'local-quick-select-6',
    LOCAL_QUICK_SELECT_7            : 'local-quick-select-7',
    LOCAL_QUICK_SELECT_8            : 'local-quick-select-8',
    LOCAL_QUICK_SELECT_9            : 'local-quick-select-9',
    LOCAL_QUICK_SELECT_10           : 'local-quick-select-10',
    ENABLE_FAVORITES                : 'enable-favorites',
    LANGUAGE                        : 'language',
};

export const ITEMS_PER_PAGE = 10;

// text first, then images, order matters
export const CLIPBOARD_MIMETYPES = [
    'text/plain;charset=utf-8',
    'UTF8_STRING',
    'text/plain',
    'STRING',
    'image/gif',
    'image/png',
    'image/jpg',
    'image/jpeg',
    'image/webp',
    'image/svg+xml',
    'text/html',
];

// mirrors the popup-position-mode schema
export const PopupPositionMode = {
    CURSOR: 0,
    WINDOW_CENTER: 1,
};
